name: gallery
run-name: Setting up the photo gallery database
on: [push]
jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
      - name: Test output
        run: echo "Here is a test"
  connect-remote:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v3
    - name: Show Databases
      run: mysql -h hostname --port 3306 -username -password -e "Show Databases"